### ISSUE TITLE
ASMARA Icon Needed | Webserver

### ISSUE THREAD

**Issue by reggietorres** [A-c0rN/ASMARA#16]
If anyone could provide an icon for ASMARA, that would be awesome.. @A-c0rN

**Comment by A-c0rN** [comment]
ASMARA doesn't have a logo yet!
I need to work on that, but I am no designer.

**Comment by reggietorres** [comment]
No Worries, let me know when we get one

**Comment by physprop** [comment]
I have made some logos. Ill add these into a folder and make a PR.

![asmara-black-text](https://github.com/A-c0rN/ASMARA/assets/26415248/e3fe6d96-807d-4066-b734-435b664bc2da)
![asmara-white-text](https://github.com/A-c0rN/ASMARA/assets/26415248/7c7bec7d-feb8-41d3-bdce-d447098c7f9f)
![asmara-white-text](https://github.com/A-c0rN/ASMARA/assets/26415248/be239a86-779e-4983-82ba-f57a07e102bc)
![asmara-black-text](https://github.com/A-c0rN/ASMARA/assets/26415248/d2928c99-836f-4b78-b59d-18f4baa8b963)
![asmara-logo-only](https://github.com/A-c0rN/ASMARA/assets/26415248/1620e446-ebc1-41f0-b22b-93f579ddcc61)

**Comment by A-c0rN** [comment]
physprop is a good long time contributor, I approve these!
👍

**Comment by reggietorres** [comment]
Perfect!
