### ISSUE TITLE
Need a Statistics Logo | Webserver

### ISSUE THREAD

**Issue by reggietorres** [A-c0rN/ASMARA#32]
if i could get an icon/logo for statistics, that would be great

**Comment by A-c0rN** [comment]
@physprop can you tackle this? You got the logos down pat lol

**Comment by physprop** [comment]
What kind of logo are we thinking of here? Just a generic icon for analytics? Can you provide a screenshot of where this will be used for context?

**Comment by reggietorres** [comment]
atm im using one of the other logos for it, but this is where it would go atm
![image](https://github.com/A-c0rN/ASMARA/assets/156597761/b7161337-415b-4667-ad1a-3beb0acbc658)

**Comment by physprop** [comment]
![analytics-with-hexagon](https://github.com/A-c0rN/ASMARA/assets/26415248/b927f629-640e-4388-88f9-6f4591a68665)
Give this one a shot @reggietorres. LMK if you want any changes.
(for note (icon comes from google's material design library, which is open source.)

**Comment by reggietorres** [comment]
Perfect!
