### ISSUE TITLE
Need SAME Documentation

### ISSUE THREAD

**Issue by reggietorres** [A-c0rN/ASMARA#35]
I don't exactly remember how far up the duration number in the EAS SAME code can go up, so if someone could provide documentation for that, would be great, also need python code for generating JJJHHMM

**Comment by A-c0rN** [comment]
The max timestamp duration is 9930 In theory, but most boxes do 2400, 1200, or 0600.

**Comment by A-c0rN** [comment]
Code for generating JJJHHMM is in ASMARAs encoding subroutines, look in there :3

**Comment by reggietorres** [comment]
> The max timestamp duration is 9930 In theory, but most boxes do 2400, 1200, or 0600.

So is there such thing as 08:44, or is it how i thought it was, where it goes up in 5 intervals

which would be

08:45

08:50

08:55

etc etc

**Comment by reggietorres** [comment]
[solved](https://en.wikipedia.org/wiki/Specific_Area_Message_Encoding)
