### ISSUE TITLE
Playout Bug

### ISSUE THREAD

**Issue by ManMacho** [A-c0rN/ASMARA#41]
'[PLAYOUT] WARNING > *** UNKNOWN STATE: This is a bug! ***'
'[PLAYOUT] WARNING > *** Killing current patch ***'

**Comment by reggietorres** [comment]
i get that alot, i usually ignore it and it still works, i honestly dont know why it does it, if you can ignore it, ignore it, if you can't, get back to me

**Comment by ManMacho** [comment]
> i get that alot, i usually ignore it and it still works, i honestly dont know why it does it, if you can ignore it, ignore it, if you can't, get back to me

alright, just trying to setup icecast, hoping thats not gonna interfere with it at all.

**Comment by reggietorres** [comment]
If you have issues with setting up a config, which can be a bit confusing, let me know il help you out

**Comment by ManMacho** [comment]
> If you have issues with setting up a config, which can be a bit confusing, let me know il help you out

alright

**Comment by ManMacho** [comment]
> If you have issues with setting up a config, which can be a bit confusing, let me know il help you out

im a bit confused on the emulation part - what are my options to put there?

**Comment by reggietorres** [comment]
> > If you have issues with setting up a config, which can be a bit confusing, let me know il help you out
> 
> im a bit confused on the emulation part - what are my options to put there?

that is for telling the endec to mimic a real endec sound wise, you don't have to put anything there, but i personally set mine to DIGITAL

**Comment by reggietorres** [comment]
for options you can check the documents for EASGen

**Comment by ManMacho** [comment]
> for options you can check the documents for EASGen

ah i see, im just having issues with it saying 'alert is VERY expired' now, when its not..

**Comment by reggietorres** [comment]
Thats cause this year is a leap year, it will be fixed soon im sure

**Comment by ManMacho** [comment]
> Thats cause this year is a leap year, it will be fixed soon im sure

ah, alright.

**Comment by reggietorres** [comment]
> > Thats cause this year is a leap year, it will be fixed soon im sure
> 
> Will this still relay the alerts or no?

Not until the bug is fixed, all alerts are currently classified as VERY EXPIRED. because its a leap year, so the software is unusable except for the AutoDJ part of it.

**Comment by ManMacho** [comment]
> > > Thats cause this year is a leap year, it will be fixed soon im sure
> > 
> > 
> > Will this still relay the alerts or no?
> 
> Not until the bug is fixed, all alerts are currently classified as VERY EXPIRED. because its a leap year, so the software is unusable except for the AutoDJ part of it.

Yikes, does the logger even work?

**Comment by reggietorres** [comment]
> > > > Thats cause this year is a leap year, it will be fixed soon im sure
> > > 
> > > 
> > > Will this still relay the alerts or no?
> > 
> > 
> > Not until the bug is fixed, all alerts are currently classified as VERY EXPIRED. because its a leap year, so the software is unusable except for the AutoDJ part of it.
> 
> Yikes, does the logger even work?

why would it log expired alerts lol? even if the alert isn't expired in the time it was made sense, the program thinks it is because of the leap year. so it won't log it, Yes the logger works, but it doesn't log expired alerts..

**Comment by ManMacho** [comment]
okay, hopefully it gets fixed soon i guess.

**Comment by reggietorres** [comment]
Please close this issue, someone might get confused and think this is where we are discussing the bug, and potential fixes. we will be doing that in #37
