### ISSUE TITLE
OpenSSL Certificate Issue?

### ISSUE THREAD

**Issue by ManMacho** [A-c0rN/ASMARA#42]
![image](https://github.com/A-c0rN/ASMARA/assets/161545642/63acabab-9d34-44d9-9df2-d328c5b428f8)

Not sure.

**Comment by physprop** [comment]
Commenting on this to point someone in the right direction in case this happens again.

Looks like this is an SSL issue with the Icecast server that ASMARA was playing out to. It can be resolved using either non-SSL certificates or a trusted PKI.
