### ISSUE TITLE
Error InvalidSAME, Invalid data in SAME Message, Invalid code in FIPS data.

### ISSUE THREAD

**Issue by spokentester299** [A-c0rN/ASMARA#50]
![image](https://github.com/A-c0rN/ASMARA/assets/20000144/6d330bf3-f79f-4848-8a5e-e5aa69e2ecb4)

Error started yesterday and now nothing will relay after recieving this message. It will say "Relaying ASAP" but will never go over the station.  Will  provide full log if needed. the Discord webhook will say "Receiving Alert" but never say "Alert Sent" after getting this error. 

This seems to happen on any monitor, no matter the link. Sometimes the monitor that gives the error decodes, sometimes not.

I have also uninstalled/reinstalled EAS2Text to no avail. 

Thank you for your time 

System Specs:
Running Ubuntu 24 in VirtualBox (host os: windows 10)
4 GB ram
50 GB storage

**Comment by physprop** [comment]
have you modified ASMARA at all? and does this issue happen with any other station

**Comment by spokentester299** [comment]
I have modified ASMARA's config file (for normal stuff), and this happens with pretty much all of them. I have changed around stations and it makes no difference.  Other than that, no.

**Comment by spokentester299** [comment]
Python v3.12.3 (main)
samedec 0.4.0

and here is the config (blacked out is sensetive stuff)
![image](https://github.com/A-c0rN/ASMARA/assets/20000144/07bcb758-38e9-4377-9265-faadd32161d2)
![image](https://github.com/A-c0rN/ASMARA/assets/20000144/64f774a3-df2c-4c58-b1bd-20dd021de105)

**Comment by physprop** [comment]
Ah, i see the problem. You have a "-" in your callsign, which is an invalid character when it comes to callsigns. I would swap it over to a "/".
