### ISSUE TITLE
Icecast-based Playout (External Audio Input)

### ISSUE THREAD

**Issue by TamShep** [A-c0rN/ASMARA#8]
Why not add the ability to use an Icecast server to feed the AutoDJ in the software? I feel this would be very helpful for those who use external playout systems and stuff and would make it not require the presence of a silence detector and interrupter (Voicemeeter, FFMPEG, etc), handling it entirely internally.

**Comment by A-c0rN** [comment]
This is in the plan for the Playout System Rewrite in the Projects, but the Playout system is going to completely change. 
The current playout system was supposed to be temporary, and the new system will use Net / Unix pipes to allow a user to connect it to any audio system that they need, such as a Python Net Wrapper, FFMPEG, Icecast, Ect. 
This not only properly segments this to what it needs to do, but also gives the user more freedom for connectivity to systems, both commercial and custom.
This should be an *endec*, not a full playout system per se, so the player should handle the EAS only, not the audio.
Great idea, though!
